APP.Main=(function(){var LAZY_LOAD_THRESHOLD=300;var $=document.querySelector.bind(document);var stories=null;var storyStart=0;var count=100;var main=$('main');var inDetails=!1;var storyLoadCount=0;var mainHtml=null;var storyHtml=null;var localeData={data:{intl:{locales:'en-US'}}};var tmplStory=$('#tmpl-story').textContent;var tmplStoryDetails=$('#tmpl-story-details').textContent;var tmplStoryDetailsComment=$('#tmpl-story-details-comment').textContent;if(typeof HandlebarsIntl!=='undefined'){HandlebarsIntl.registerWith(Handlebars)}else{var intlRelative=/, {{ formatRelative time }}/;tmplStory=tmplStory.replace(intlRelative,'');tmplStoryDetails=tmplStoryDetails.replace(intlRelative,'');tmplStoryDetailsComment=tmplStoryDetailsComment.replace(intlRelative,'')}
var storyTemplate=Handlebars.compile(tmplStory);var storyDetailsTemplate=Handlebars.compile(tmplStoryDetails);var storyDetailsCommentTemplate=Handlebars.compile(tmplStoryDetailsComment);function buildStory(key,details){var elementId='#s-'+key;details.time*=1000;var story=document.querySelector(elementId);var html=storyTemplate(details);story.innerHTML=html;story.addEventListener('click',onStoryClick.bind(this,details));story.classList.add('clickable');storyLoadCount--}
function onStoryData(key,details){window.requestAnimationFrame(buildStory.bind(this,key,details))}
var Story=function(details){this.details=details};function onStoryClick(details){window.requestAnimationFrame(showStory.bind(this,details.id));if(details.url)
details.urlobj=new URL(details.url);var comment;var commentsElement;var storyHeader;var storyContent;var storyDetailsHtml=storyDetailsTemplate(details);var kids=details.kids;var commentHtml=storyDetailsCommentTemplate({by:'',text:'Loading comment...'});var old=document.getElementsByClassName('story-details');if(old.length>0){document.getElementById(old[0].id).outerHTML=''}
var storyDetails=document.createElement('section');storyDetails.setAttribute('id','sd-'+details.id);storyDetails.classList.add('story-details');storyDetails.innerHTML=storyDetailsHtml;document.body.appendChild(storyDetails);commentsElement=storyDetails.querySelector('.js-comments');storyHeader=storyDetails.querySelector('.js-header');storyContent=storyDetails.querySelector('.js-content');var closeButton=storyDetails.querySelector('.js-close');closeButton.addEventListener('click',hideStory.bind(this,details.id));var headerHeight=storyHeader.getBoundingClientRect().height;storyContent.style.paddingTop=headerHeight+'px';if(typeof kids==='undefined')
return;for(var k=0;k<kids.length;k++){comment=document.createElement('aside');comment.setAttribute('id','sdc-'+kids[k]);comment.classList.add('story-details__comment');comment.innerHTML=commentHtml;commentsElement.appendChild(comment);APP.Data.getStoryComment(kids[k],function(commentDetails){commentDetails.time*=1000;var comment=commentsElement.querySelector('#sdc-'+commentDetails.id);comment.innerHTML=storyDetailsCommentTemplate(commentDetails,localeData)})}}
function showStory(id){if(inDetails)
return;inDetails=!0;var storyDetails=$('#sd-'+id);var left=null;if(!storyDetails)
return;document.body.classList.add('details-active');storyDetails.style.opacity=1;function animate(){var storyDetailsPosition=storyDetails.getBoundingClientRect();if(left===null)
left=storyDetailsPosition.left;left-=left*0.1;if(Math.abs(left)>0.5){storyDetails.style.left=left+'px';setTimeout(animate,4)}
else left=0}
setTimeout(animate,4)}
function hideStory(id){if(!inDetails)
return;var storyDetails=$('#sd-'+id);var left=0;document.body.classList.remove('details-active');storyDetails.style.opacity=0;function animate(){var mainPosition=main.getBoundingClientRect();var storyDetailsPosition=storyDetails.getBoundingClientRect();var target=mainPosition.width+100;left+=(target-storyDetailsPosition.left)*0.1;if(Math.abs(left-target)>0.5){setTimeout(animate,4)}else{left=target;inDetails=!1}
storyDetails.style.left=left+'px'}
setTimeout(animate,4)}
main.addEventListener('scroll',function(){var header=$('header');var headerTitles=header.querySelector('.header__title-wrapper');var scrollTopCapped=Math.min(70,main.scrollTop);var scaleString='scale('+(1-(scrollTopCapped/300))+')';header.style.height=(156-scrollTopCapped)+'px';headerTitles.style.webkitTransform=scaleString;headerTitles.style.transform=scaleString;if(main.scrollTop>70)
document.body.classList.add('raised');else document.body.classList.remove('raised');var loadThreshold=(main.scrollHeight-main.offsetHeight-LAZY_LOAD_THRESHOLD);if(main.scrollTop>loadThreshold)
loadStoryBatch()});function loadStoryBatch(){if(storyLoadCount>0)
return;storyLoadCount=count;var end=storyStart+count;for(var i=storyStart;i<end;i++){if(i>=stories.length)
return;var key=String(stories[i]);var story=document.createElement('div');story.setAttribute('id','s-'+key);story.classList.add('story');story.innerHTML=storyTemplate({title:'...',score:'-',by:'...',time:0});main.appendChild(story);APP.Data.getStoryById(stories[i],onStoryData.bind(this,key))}
storyStart+=count}
APP.Data.getTopStories(function(data){stories=data;loadStoryBatch();main.classList.remove('loading')})})()
